config/routes.rb
OpgLpa::Application.routes.draw do

  root "content#homepage"

  get '/help' => 'content#guidance'

  resources :lpas do
    get '/preview_pdf' => 'lpas#preview_pdf'
    get '/get_pdf' => 'lpas#get_pdf'
    get '/pdf' => 'lpas#pdf'

    resources :build, controller: 'lpas/build'
    resources :registration, controller: 'lpas/registration'
    collection do
      get :find
    end
    resources :attorneys
    resources :replacement_attorneys
    resources :people_to_be_told
  end

  resources :applicants, only: [:new, :create]

  namespace 'users' do
    get  '/sign_up' => 'registrations#new',    as: :new_registration
    post '/'        => 'registrations#create', as: :registration

    get '/confirmations/:confirmation_token' => 'confirmations#show'

    get  '/sign_in' => 'sessions#new',    as: :new_session
    post '/sign_in' => 'sessions#create', as: :session
    delete '/sign_out' => 'sessions#destroy', as: :destroy_session
  end

  resource :feedback

end

app/controllers/people_to_be_told_controller.rb
class PeopleToBeToldController < ApplicationController

  def new
    @lpa = Lpa.find(params[:lpa_id])
    @person_to_be_told = PersonToBeTold.new

    render :layout => !request.xhr?
  end

  def create
    @lpa = Lpa.find(params[:lpa_id])
    @person_to_be_told = PersonToBeTold.new(params[:person_to_be_told])
    @lpa.people_to_be_told << @person_to_be_told

    if @lpa.save
      respond_to do |format|
        format.html { redirect_to lpa_build_path(lpa_id: @lpa, id: :people_to_be_told) }
        format.json { render json: { success: true } }
      end
    else
      respond_to do |format|
        format.html { render template: "/people_to_be_told/new" }
        format.json { render json: { errors: @person_to_be_told.errors } }
      end
    end
  end

end

app/views/people_to_be_told/new.html.haml
= render "shared/create_header"

.article-container.group
  %article.group{:role => "article"}
    .inner
      %h2.header Enter person to be told details
      = form_for @person_to_be_told, :url => lpa_people_to_be_told_path(@lpa), :html => { :class => 'form js-validate-form', 'novalidate' => '' } do |person_to_be_told_form|
        = render "shared/validation_summary", :form_object => person_to_be_told_form.object
        = render :partial => '/shared/person_form', :locals => {:person_form => person_to_be_told_form, :without_email => true, :without_phone => true}
        %p.action.group
          = person_to_be_told_form.submit "Save details", class: "button"
          = link_to "Cancel", "#", class: "button-secondary js-popup-close"