config/routes.rb
OpgLpa::Application.routes.draw do

  root "content#homepage"

  get '/help' => 'content#guidance'

  resources :lpas do
    get '/preview_pdf' => 'lpas#preview_pdf'
    get '/get_pdf' => 'lpas#get_pdf'
    get '/pdf' => 'lpas#pdf'

    resources :build, controller: 'lpas/build'
    resources :registration, controller: 'lpas/registration'
    collection do
      get :find
    end
    resources :attorneys
    resources :replacement_attorneys
    resources :people_to_be_told
  end

  resources :applicants, only: [:new, :create]

  namespace 'users' do
    get  '/sign_up' => 'registrations#new',    as: :new_registration
    post '/'        => 'registrations#create', as: :registration

    get '/confirmations/:confirmation_token' => 'confirmations#show'

    get  '/sign_in' => 'sessions#new',    as: :new_session
    post '/sign_in' => 'sessions#create', as: :session
    delete '/sign_out' => 'sessions#destroy', as: :destroy_session
  end

  resource :feedback

end

app/views/index/index.html.haml
%header.page-header.inner
  %hgroup
    %h1
      %span Service
      Make a lasting power of attorney
      %small.beta beta

.article-container.group
  %article.group{:role => "article"}
    .inner
      .page-intro
        %p This tool will help you to create a #{link_to "lasting power of attorney", "#", { :class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:lpa-basics" }} (LPA) that can be registered in England and Wales. It will also support you in signing and applying to register an LPA with the Office of the Public Guardian (OPG).
        %p Remember, an LPA must be registered before it can be used.

        -#
          .help-notice.application-notice
            %p Please be aware there is planned maintenance to this site on Friday 8th November between 17:00 - 22:00 where the service will be unavailable.

        %p.homepage-cta
          %strong Follow the steps below, or #{link_to "sign in", users_new_session_path}.

      %ol.make-LPA.steps{"aria-role" => "list"}
        %li
          = image_tag "homepage/pictogram-create-lpa.png"
          %p.step-title
            %strong Create an LPA
          %p Use this digital tool to fill in the LPA form. When it’s complete you can print an LPA document.
          %p= link_to "Create an LPA now", users_new_registration_path, {:class => "create-lpa button", :role => "button"}
        %li
          = image_tag "homepage/pictogram-sign-lpa.png"
          %p.step-title
            %strong Sign the LPA
          %p Several people must sign the LPA document in a set order. We’ll explain who needs to sign and when.
          %p= link_to "More about signing", "#signing-the-lpa", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:signing-the-lpa"}
        %li
          = image_tag "homepage/pictogram-register-lpa.png"
          %p.step-title
            %strong Register the LPA
          %p When you’re ready, sign back in here to complete a registration form and pay the £110 fee. Then post the LPA and registration form to OPG.
          %p= link_to "More about registering", "#registering-the-lpa", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:registering-the-lpa"}
        %li
          = image_tag "homepage/pictogram-receive-lpa.png"
          %p.step-title
            %strong Receive your LPA
          %p OPG will return your registered and stamped LPA – ready to use when you need it.

      %hr

      %h2 Before you begin
      %p If you’re making your first LPA, there a few things you need to know and to think about. These help topics are a good place to start:
      %p= link_to "LPA basics", "#lpa-basics", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:lpa-basics"}
      %p= link_to "About this tool", "#about-this-tool", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:about-this-tool"}

      %h2 Quick questions
      %p Here are some answers to common questions. You’ll find lots more guidance on the decisions you need to make, and the information you need to add, as you progress through the LPA tool.

      %details
        %summary{"aria-expanded" => "false", "data-journey-click" => "stageprompt.lpa:help.inline:/:how-much-does-it-cost-to-apply-to-register-an-lpa", role: "button"} How much does it cost to apply to register an LPA?
        %p There's a £110 application fee to register an LPA, paid by or on behalf of the donor – that’s the person who’s making the LPA. If the donor has an income below £12,000, or gets certain benefits, they might qualify for a lower fee, or the fee might be waived altogether.
        %p #{link_to "Fees and reductions", "#fees-and-reductions", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:fees-and-reductions"}}
        %p Remember, an LPA must be registered before it can be used.
      %details
        %summary{"aria-expanded" => "false", "data-journey-click" => "stageprompt.lpa:help.inline:/:how-long-does-it-take-to-register-an-lpa", role: "button"} How long does it take to register an LPA?
        %p It takes at least 4 weeks. This time is counted from when the completed and signed LPA is received by the Office of the Public Guardian. This time – known as the ‘waiting period’ – allows people involved in the LPA to raise any concerns before it’s registered.
        %p We also use the time to check that there are no mistakes in the LPA, including anything that would make it invalid or unworkable. We’ll get in touch if you need to correct something before the LPA can be registered.
        %p It’s a good idea to apply to register an LPA sooner rather than later.
        %p #{link_to "Registering an LPA", "#registering-the-lpa", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:registering-the-lpa"}}
      %details
        %summary{"aria-expanded" => "false", "data-journey-click" => "stageprompt.lpa:help.inline:/:can-i-do-it-all-using-this-tool", role: "button"} Can I do it all using this tool?
        %p Not quite. This digital tool will help you make an LPA and support you in applying to registering it. You’ll need to print a copy though, and get this signed, as well as completing some of the registration tasks offline. Then you’ll need to post the LPA to OPG for registration.
        %p We’ll explain what you need to do as you complete each step.
        %p #{link_to "About this tool", "#about-this-tool", {:class => "open-help-system popup-link", "data-journey-click" => "stageprompt.lpa:help:about-this-tool"}}
      %details
        %summary{"aria-expanded" => "false", "data-journey-click" => "stageprompt.lpa:help.inline:/:what-does-beta-mean", role: "button"} What does beta mean?
        %p Beta means this is a new online tool and we’re still testing and improving it. However, the tool is ready to use and will help you make and apply to register your LPA.
        %p The tool has already gone through rigorous testing to make sure it works well and that information you enter is secure. It’s just that we’re still looking for ways to make it even better.
        %p
          We welcome your feedback. Please use the tool and let us know what you think. #{link_to "Email us your comments", "mailto:LPAdigitalfeedback@PublicGuardian.gsi.gov.uk?subject=Digital%20LPA%20Feedback"}.

      %hr
      %p= link_to "Terms and conditions", "#"