config/routes.rb
OpgLpa::Application.routes.draw do

  root "content#homepage"

  get '/help' => 'content#guidance'

  resources :lpas do
    get '/preview_pdf' => 'lpas#preview_pdf'
    get '/get_pdf' => 'lpas#get_pdf'
    get '/pdf' => 'lpas#pdf'

    resources :build, controller: 'lpas/build'
    resources :registration, controller: 'lpas/registration'
    collection do
      get :find
    end
    resources :attorneys
    resources :replacement_attorneys
    resources :people_to_be_told
  end

  resources :applicants, only: [:new, :create]

  namespace 'users' do
    get  '/sign_up' => 'registrations#new',    as: :new_registration
    post '/'        => 'registrations#create', as: :registration

    get '/confirmations/:confirmation_token' => 'confirmations#show'

    get  '/sign_in' => 'sessions#new',    as: :new_session
    post '/sign_in' => 'sessions#create', as: :session
    delete '/sign_out' => 'sessions#destroy', as: :destroy_session
  end

  resource :feedback

end

app/views/shared/_completed_sections.html.haml
- lpa_overview(@lpa).each_with_index do |text, index|
  %section#lpa-type.section.complete
    %p.accordion-summary
      %a{:href => back_path(params[:controller], text[0])}
        %span.edit{:style => "float:right"} edit
        #{index+1}. #{text[1]}

app/views/shared/_create_header.html.haml
- if  !request.xhr?
  = render 'shared/progress_nav', :active_state => "create"
  %header.page-header.inner
    %h1 Create a lasting power of attorney
    %p We'll use your answers to the questions that follow to create an LPA that you can save and print, sign and then apply to register. We'll save your LPA as you progress so you don't need to do it all in one go.

app/views/shared/_global_nav.html.haml
#global-nav.js-toggle-nav
  .inner
    %nav.content
      %ul#navigation
        %li.user= session[:applicant_name] ? session[:applicant_name] + ":" : ''
        -#
          %li
            %a{:href => ""} Your details
        %li= link_to "Your LPAs", lpas_path
        %li= link_to "Sign out", users_destroy_session_path, method: :delete

app/views/shared/_lpa_details_inset.html.haml
%h3 LPA for #{@lpa.type}
%ul
  %li For #{@lpa.donor.full_name}.
  %li Created on 01/11/2013.
.LPA-actions
  %a{:href => "#"} View or edit this LPA
  &nbsp;|&nbsp;
  %a{:href => "#"} Delete this LPA

app/views/shared/_nav.html.haml
#global-nav.js-toggle-nav
  .inner
    %nav.content
      %ul#navigation
        %li.user= session[:applicant_name] || ''
        %li
          %a{:href => ""} Your details
        %li= link_to "Your LPAs", lpas_path
        %li= link_to "Sign out", users_destroy_session_path, method: :delete

app/views/shared/_person_form.html.haml
- show_other_names ||= false
- show_dob ||= false
- without_email ||= false
- without_phone ||= false
- show_dx_address ||= false
- show_legends ||= false


%fieldset
  - if show_legends
    %legend Name
  = input_for(person_form, "title", {}, {:class => "js-TitleSwitch"})
  = input_for(person_form, "first_name", {}, {:required => "", "parsley-minlength" => "2"})
  = input_for(person_form, "middle_names", {:label_override => "Middle names (optional)"})
  = input_for(person_form, "last_name", {}, {:required => "", "parsley-minlength" => "2"})
  - if show_other_names
    %details
      %summary.hint{:role => "button", "aria-expanded" => "false"} Is this person known by any other names?
      .group
        %label#othername-label{:for => "othername"} Other names
        %input#othername{:name => "othername", :type => "text", :autocomplete => "off", :maxlength => "100"}

- if show_dob
  %fieldset
    - if show_legends
      %legend Date of Birth
    = input_for(person_form, "date_of_birth") do
      = person_form.date_select "date_of_birth", { order: [ :day, :month, :year ], start_year: (Time.now.year - 120), prompt: { day: :day, month: :month, year: :year } }, {:required => ""}

- unless without_email
  = input_for(person_form, "email", {:type => "email", :label_override => "Email (optional)"})

- unless without_phone
  = input_for(person_form, "phone", {:label_override => "Phone (optional)"})

.js-PostcodeLookup
  %fieldset.address-fieldset.js-PostcodeLookup__postal-add
    - if show_legends
      %legend Address
    = person_form.fields_for person_form.object.address do |person_address_form|
      = input_for(person_address_form, "address_line1", {:label_override => "Street"})
      = input_for(person_address_form, "address_line2", {:label_override => false})
      = input_for(person_address_form, "address_line3", {:label_override => false})
      = input_for(person_address_form, "town")
      = input_for(person_address_form, "county")
      = input_for(person_address_form, "post_code", {}, {:class => "postcode"})
      = input_for(person_address_form, "country")

  %fieldset.address-fieldset.js-PostcodeLookup__dx-add
    - if show_dx_address
      .group
        %label{:for => "dx_number"} DX number
        %input#dx_number{:name => "dx_number", "type" => "text"}
      .group
        %label{:for => "dx_exchange"} DX exchange
        %input#dx_exchange{:name => "dx_exchange", "type" => "text"}
      -# = input_for(person_address_form, "dx_number", {:label_override => "DX number"})
      -# = input_for(person_address_form, "dx_exchange", {:label_override => "DX exchange"})

app/views/shared/_preview_pdf_link.html.haml
%ul.secondary-actions
  %li= link_to("Download preview of LPA (PDF)", {:controller => "/lpas", :action => "preview_pdf", :remote => true}, :target => '_blank', :class => "js-preview-pdf")

app/views/shared/_progress_nav.html.haml
%nav.progress-indicator.group{:role => "navigation"}
  %ol.group
    %li{:class => defined?(active_state) && (active_state == "about") ? "active" : ""} About you
    %li{:class => defined?(active_state) && (active_state == "create") ? "active" : ""} Create the LPA
    %li{:class => defined?(active_state) && (active_state == "sign") ? "active" : ""} Sign the LPA
    %li{:class => defined?(active_state) && (active_state == "register") ? "active" : ""} Register the LPA
    %li{:class => defined?(active_state) && (active_state == "done") ? "active" : ""} Done

app/views/shared/_register_header.html.haml
- if  !request.xhr?
  = render 'shared/progress_nav', :active_state => "register"
  %header.page-header.inner
    %h1 Register a lasting power of attorney

app/views/shared/_validation_summary.html.haml
- if form_object.errors.any?
  .validation-summary.group{:role => "alert", "aria-labbelledby" => "error-heading"}
    %h1{:id => "error-heading"} There was a problem submitting the form
    %p Because of the following problems:
    %ol
      - form_object.errors.messages.each do |field, error|
        %li
          %a{:href => "##{field}_label"} #{field.to_s.humanize} #{form_object.errors[field].first}