config/routes.rb
OpgLpa::Application.routes.draw do

  root "content#homepage"

  get '/help' => 'content#guidance'

  resources :lpas do
    get '/preview_pdf' => 'lpas#preview_pdf'
    get '/get_pdf' => 'lpas#get_pdf'
    get '/pdf' => 'lpas#pdf'

    resources :build, controller: 'lpas/build'
    resources :registration, controller: 'lpas/registration'
    collection do
      get :find
    end
    resources :attorneys
    resources :replacement_attorneys
    resources :people_to_be_told
  end

  resources :applicants, only: [:new, :create]

  namespace 'users' do
    get  '/sign_up' => 'registrations#new',    as: :new_registration
    post '/'        => 'registrations#create', as: :registration

    get '/confirmations/:confirmation_token' => 'confirmations#show'

    get  '/sign_in' => 'sessions#new',    as: :new_session
    post '/sign_in' => 'sessions#create', as: :session
    delete '/sign_out' => 'sessions#destroy', as: :destroy_session
  end

  resource :feedback

end

app/models/attorney.rb
class Attorney < ActiveResource::Base
  self.site = Rails.configuration.api_uri

  schema do
    string 'title', 'first_name', 'middle_names', 'last_name'
    string 'date_of_birth'
    string 'email'
    string 'phone'
    string 'occupation', 'relationship_to_donor'
  end

  has_one :address

  def initialize(*args)
    # Make sure we always have associations assigned, so that activeresource doesn't request them
    args[0] ||= {}
    args[0] = {
      :address => Address.new
    }.merge(args[0])
    super(*args)
  end

  def full_name
    "#{title} #{first_name} #{last_name}"
  end
end

app/controllers/attorneys_controller.rb
class AttorneysController < ApplicationController

  def new
    @lpa = Lpa.find(params[:lpa_id])
    @attorney = Attorney.new

    #render :layout => !request.xhr?
  end

  def create
    @lpa = Lpa.find(params[:lpa_id])
    @attorney = Attorney.new(attorney_params)
    @lpa.send(attorney_relation) << @attorney


    if @lpa.save
      respond_to do |format|
        format.html { redirect_to lpa_build_path(lpa_id: @lpa, id: attorney_relation) }
        format.json { render json: { success: true } }
      end
    else
      respond_to do |format|
        format.html { render template: "/#{attorney_relation}/new" }
        format.json { render json: { errors: @attorney.errors } }
      end        
    end
  end

  def destroy
    @lpa = Lpa.find(params[:lpa_id])

    if attorney = @lpa.attorneys.detect {|x| x.id == params[:id]}
      attorney._destroy = true
    end
    if replacement_attorney = @lpa.replacement_attorneys.detect {|x| x.id == params[:id]}
      replacement_attorney._destroy = true
    end

    @lpa.save

    @lpa = Lpa.find(params[:lpa_id])
    redirect_to lpa_build_path(lpa_id: @lpa, id: attorney_relation)
  end

  def attorney_relation
    :attorneys
  end

  private

  def attorney_params
    create_single_date_field :attorney
    params[:attorney]
  end

end

app/views/attorneys/new.html.haml
= render "shared/create_header"

.article-container.group
  %article.group{:role => "article"}
    .inner
      %h2.header Enter attorney details
      = form_for @attorney, :url => lpa_attorneys_path(@lpa), :html => { :class => 'form js-validate-form', 'novalidate' => '' } do |attorney_form|
        = render "shared/validation_summary", :form_object => attorney_form.object
        %p.role-select.group
          = link_to "Using a trust corporation?", new_lpa_attorney_path(@lpa), {:class => 'js-form-popup', "data-form" => "attorney-trust-corporation"}
        = render :partial => '/shared/person_form', :locals => {:person_form => attorney_form, :show_dob => true, :show_dx_address => true, :without_email => true, :without_phone => true}
        %fieldset
          %p.hint The following fields are optional.
          = input_for(attorney_form, "email", {:type => "email"})
          = input_for(attorney_form, "phone")
          .group
            %label#relationshipToDonor-label.optional{:for => "relationshipToDonor"}
              Relationship to donor
              %span.visuallyhidden (optional)
            %select#relationshipToDonor{:name => "relationshipToDonor"}
              %option{:value => "", :selected => "selected"} Please select
              %option{:value => "Partner"} Spouse or civil partner of the donor
              %option{:value => "Child"} Child of donor
              %option{:value => "Solicitor"} Solicitor acting for the donor
              %option{:value => "Other"} Other (please specify)...
          .group{:style => "display: none;"}
            %label#relationshipToDonorOther-label.optional{:for => "relationshipToDonorOther"} Specify relationship to donor
            %input#relationshipToDonorOther{:name => "relationshipToDonorOther", :type => "text", :autocomplete => "off", :maxlength => "100"}
        %p.action.group
          = attorney_form.submit "Save details", class: "button"
          = link_to "Cancel", "#", class: "button-secondary js-popup-close"